algoritmo "semnome"
// Função :
// Autor :
// Data : 10/04/2023
// Seção de Declarações 
var
vezes, valor, ctd, final : inteiro

inicio
// Seção de Comandos 

escreval("Digite o primeiro valor:")
leia(vezes)
escreval("Digite o segundo valor:")
leia(valor)

para ctd de 1 ate vezes passo 1 faca

     final <- final + valor

fimpara

escreval("O valor da multiplicação de ", vezes, " x", valor, " =", final)

fimalgoritmo
