algoritmo "semnome"
// Função :
// Autor :
// Data : 10/04/2023
// Seção de Declarações 
var
frase : literal
linha, limite : inteiro
inicio
// Seção de Comandos 

linha <- 1
escreval("digite a frase que deseja repetir")
leia(frase)
escreval("digite quantidade de vezes que deseja repetir")
leia(limite)

para linha de 1 ate limite passo 1 faca
     escreval(linha, " - ", frase)
fimpara


fimalgoritmo
