algoritmo "semnome"
// Função :
// Autor :
// Data : 17/04/2023
// Seção de Declarações
var
num1, num2: inteiro
inicio
escreva("Digite o número 1: ")
leia(num1)
escreva("Digite o número 2: ")
leia(num2)
enquanto num1 <> num2 faca
   se num1 > num2 entao
      escreval("Decrescente")
   senao
      escreval("Crescente")
   fimse
escreva("Digite o número 1: ")
leia(num1)
escreva("Digite o número 2: ")
leia(num2)
   fimenquanto

fimalgoritmo
